### ISSUE TITLE
Where we can download model

### ISSUE THREAD

**Issue by MyraBaba** [AishahAADU/VID-Trans-ReID#3]
Hi

where  we can download the models ?

Best

**Comment by AishahAADU** [comment]
Thanks for your interest, It is currently available for download in the test section.

**Comment by MyraBaba** [comment]
@AishahAADU  thanks. is this one right : 

https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vitjx/jx_vit_base_p16_224-80ecf9dd.pth 

I am planning to replace / compare with repvgg_a0_person_reid_2048 model. Have you any experience with it ?

we will first try to convert onnx and than our quantized model for our cpu/device .

**Comment by AishahAADU** [comment]
The link you provide is imagnet pre-trained for the transformer only. Our complete model pre-trained on MARS can be downloaded from the Test section.

**Comment by MyraBaba** [comment]
@AishahAADU  Thanks.

To speed upd the comparisons ; we have 20 cameras in our building and 300 people working. Its a good test case.

Is there any example that automatically giving same ID to the same people from those 20 cameras ?
